# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
custom: ["https://bluelearn.org/pages/donate.html"]
# Add when set up:
# github: [bluelearn-org]
# open_collective: bluelearn
